// Code generated by autodig. DO NOT EDIT.
package demo

import (
	dep "github.com/cindyoshinee/autodig/dep"
	dig "go.uber.org/dig"
)

func NewdemoControllerDemo(Service *Service) (ControllerI, error) {
	var autoDigErr error
	controllerdemo := ControllerDemo{Service: Service, DigReturn: nil}
	autoDigErr = controllerdemo.Init()
	return &controllerdemo, autoDigErr
}
func demo_NewGrpcClient() *GrpcClient {
	return NewGrpcClient()
}
func NewdemoService(GrpcClient *GrpcClient, demoServiceParam struct {
	dig.In
	Logger       []Logger    `group:"loggers"`
	AbGrpcClient *GrpcClient `name:"abGrpcClient"` //public字段自动注入
}) (*Service, error) {
	var autoDigErr error
	service := Service{GrpcClient: GrpcClient, Logger: demoServiceParam.Logger, AbGrpcClient: demoServiceParam.AbGrpcClient}
	return &service, autoDigErr
}
func demo_NewAbGrpcClient() *GrpcClient {
	return NewAbGrpcClient()
}
func demo_NewLogger() Logger {
	return NewLogger()
}
func init() {
	dep.MustProvide([]interface {
	}{demo_NewGrpcClient, NewdemoService})
	dep.MustProvide([]interface {
	}{demo_NewAbGrpcClient}, dig.Name("abGrpcClient"))
	dep.MustProvide([]interface {
	}{demo_NewLogger}, dig.Group("loggers"))
	dep.MustProvide([]interface {
	}{NewdemoControllerDemo}, dig.Group("restControllers"))
}
